use_frameworks!

platform :ios, '9.0'

target 'TestDemos_Example' do
  pod 'TestDemos', :path => '../'

  target 'TestDemos_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
